services:
  app:
    image: 'url-shortener'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 3s
      retries: 5
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    env_file:
      - ./.env
    ports:
      - '6379:6379'
    command: redis-server --requirepass "${REDIS_PASS}" --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app-net
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - '3000:8080'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
    restart: on-failure

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
