CREATE TABLE IF NOT EXISTS urls (
  id         BIGSERIAL PRIMARY KEY,
  url        TEXT NOT NULL,
  alias      TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_urls_alias ON urls(alias);
CREATE INDEX IF NOT EXISTS idx_urls_user_id ON urls(user_id);