env: dev

server:
  host: 0.0.0.0
  port: '8000'
  idle_timeout: 15m
  read_timeout: 5m
  write_timeout: 5m
  std_alias_len: 5

postgres:
  host: postgres
  name: postgres
  port: '5432'
  user: postgres
  ssl_mode: disable
  options:
    max_conns: 24
    min_conns: 7
    max_conn_life_time: 1m
    max_conn_idle_time: 2m
    check_helth_period: 3m

redis:
  host: redis
  db: 0
  port: '6379'
  ttl: 10m

logger:
  level: debug
